### PR TITLE
Install missing dependencies.

### PR DESCRIPTION
**Pull request by themalkolm**
Fow whatever reason these packages are not automagically installed.
Lets fix this and after that everything installs & boots properly.

### CODE REVIEW

**Comment by DonDebonair** [comment]
Did you test this with both Debian/Ubuntu and CentOS? Package names differ sometimes, so I'll only merge if this has been tested :)

**Comment by themalkolm** [comment]
I'm using Ubuntu only.

**Comment by DonDebonair** [comment]
When you submit a PR, you should make sure that everything is checked under all supported conditions, which it this case means: it should work with Debian, Ubuntu and CentOS (see README). I cannot be 100% sure that those OSes all have the same names for their packages. Can you check if it works in Debian and CentOS as well?

**Comment by themalkolm** [comment]
Nah, keep it broken. I have not time to check all other OSes I do not care about.

**Pull request closed without merging**
